from pathlib import Path

root = Path(__file__).resolve().parents[1]

# Keep the patch workflow idempotent: it runs on every push to main.
main = root / 'main.js'
s = main.read_text(encoding='utf-8')

old_launch = "ipcMain.handle('launch-installed-game',async(_,game)=>{if(!game?.executablePath)throw new Error('Keine installierte EXE hinterlegt.');if(!fs.existsSync(game.executablePath))throw new Error('Die Spieldatei wurde nicht gefunden.');spawn(game.executablePath,[],{detached:true,stdio:'ignore'}).unref();return true;});"
new_launch = "async function launchInstalledExecutable(executablePath){if(!executablePath)throw new Error('Keine installierte EXE hinterlegt.');if(!fs.existsSync(executablePath))throw new Error('Die Spieldatei wurde nicht gefunden. Bitte installiere das Spiel erneut.');const result=await shell.openPath(executablePath);if(result)throw new Error('Spiel konnte nicht gestartet werden: '+result);return true;}\nipcMain.handle('launch-installed-game',async(_,game)=>launchInstalledExecutable(game?.executablePath));"
if old_launch in s:
    s = s.replace(old_launch, new_launch, 1)

old_install_start = "ipcMain.handle('install-game',async(_,game)=>{if(!game||!game.downloadUrl)throw new Error('Kein Download-Link vorhanden.');const folder=game.installPath||path.join(app.getPath('appData'),'SunnyLauncher','Games',safeName(game.id||game.title));fs.mkdirSync(folder,{recursive:true});const ext=game.fileName?.includes('.')?path.extname(game.fileName):'.exe';const filename=safeName(game.fileName||`${game.title||'game'}${ext}`);const destination=path.join(folder,filename),id=`${Date.now()}-${Math.random().toString(16).slice(2)}`;send('download-start',{id,title:game.title,path:folder});try{await downloadFile(game.downloadUrl,destination,id);send('download-complete',{id,title:game.title,path:destination});if(game.runInstaller&&/\\.exe$/i.test(destination))spawn(destination,[],{detached:true,stdio:'ignore'}).unref();return{ok:true,id,path:destination,installPath:folder};}catch(e){send('download-error',{id,title:game.title,error:e.message});throw e;}});"
new_install = r'''function findFileRecursive(rootDir,targetName,maxDepth=5){if(!rootDir||!fs.existsSync(rootDir))return null;const wanted=String(targetName||'').toLowerCase();const walk=(dir,depth)=>{if(depth<0)return null;let entries=[];try{entries=fs.readdirSync(dir,{withFileTypes:true});}catch{return null;}for(const entry of entries){if(entry.name.startsWith('$')&&depth>2)continue;const full=path.join(dir,entry.name);if(entry.isFile()&&entry.name.toLowerCase()===wanted)return full;if(entry.isDirectory()){const found=walk(full,depth-1);if(found)return found;}}return null;};return walk(rootDir,maxDepth);}
function setupSearchRoots(){return [...new Set([process.env.ProgramFiles,process.env['ProgramFiles(x86)'],process.env.LOCALAPPDATA,process.env.APPDATA,process.env.USERPROFILE].filter(Boolean))];}
async function runGameSetup(setupPath,game,installFolder){return await new Promise((resolve,reject)=>{const child=spawn(setupPath,[],{detached:false,stdio:'ignore',windowsHide:false});child.once('error',reject);child.once('exit',async code=>{if(code!==0)return reject(new Error('Das Setup wurde mit Exit-Code '+code+' beendet.'));let found=null;const configured=String(game.postInstallExecutable||'').trim();if(configured){if(path.isAbsolute(configured)&&fs.existsSync(configured))found=configured;else{found=findFileRecursive(installFolder,configured,6);if(!found)for(const rootDir of setupSearchRoots()){found=findFileRecursive(rootDir,configured,5);if(found)break;}}}if(!found&&game.title)for(const rootDir of [installFolder,...setupSearchRoots()]){found=findFileRecursive(rootDir,String(game.title).replace(/[^a-z0-9._-]/gi,'_')+'.exe',5);if(found)break;}if(!found)return reject(new Error('Setup abgeschlossen, aber die Startdatei wurde nicht gefunden. Hinterlege im Admin-Bereich den Namen der Start-EXE (z. B. MeinSpiel.exe).'));try{await launchInstalledExecutable(found);resolve(found);}catch(e){reject(e);}});});}
ipcMain.handle('install-game',async(_,game)=>{if(!game||!game.downloadUrl)throw new Error('Kein Download-Link vorhanden.');const folder=game.installPath||path.join(app.getPath('appData'),'SunnyLauncher','Games',safeName(game.id||game.title));fs.mkdirSync(folder,{recursive:true});const ext=game.fileName?.includes('.')?path.extname(game.fileName):'.exe';const filename=safeName(game.fileName||`${game.title||'game'}${ext}`);const destination=path.join(folder,filename),id=`${Date.now()}-${Math.random().toString(16).slice(2)}`;send('download-start',{id,title:game.title,path:folder});try{await downloadFile(game.downloadUrl,destination,id);send('download-complete',{id,title:game.title,path:destination});const isSetup=game.installType==='setup'||game.runInstaller===true;if(isSetup&&/\.exe$/i.test(destination)){const executablePath=await runGameSetup(destination,game,folder);return{ok:true,id,path:destination,installPath:folder,executablePath,setup:true};}return{ok:true,id,path:destination,installPath:folder,executablePath:destination,setup:false};}catch(e){send('download-error',{id,title:game.title,error:e.message});throw e;}});'''
if old_install_start in s:
    s = s.replace(old_install_start, new_install, 1)

main.write_text(s, encoding='utf-8')

index = root / 'index.html'
s = index.read_text(encoding='utf-8')

old_form = '<form id="upload-game-form" onsubmit="uploadGame(event)"><input id="app-title" placeholder="Spieltitel" required><textarea id="app-desc" placeholder="Beschreibung…" required></textarea><input id="app-cover" placeholder="Cover Image URL" required><input id="app-download" placeholder="Download/EXE URL" required><input id="app-version" placeholder="Version, z.B. 1.0.0" value="1.0.0"><select id="app-pricing"><option value="free">Kostenlos</option><option value="paid">Key benötigt</option></select><button class="primary" type="submit">Spiel veröffentlichen</button></form>'
new_form = '<form id="upload-game-form" onsubmit="uploadGame(event)"><input id="app-title" placeholder="Spieltitel" required><textarea id="app-desc" placeholder="Beschreibung…" required></textarea><input id="app-cover" placeholder="Cover Image URL" required><input id="app-download" placeholder="Download/EXE URL oder Setup-URL" required><input id="app-version" placeholder="Version, z.B. 1.0.0" value="1.0.0"><select id="app-install-type"><option value="direct">Direkte EXE</option><option value="setup">Setup / Installer</option></select><input id="app-post-install-exe" placeholder="Start-EXE nach Setup, z.B. MeinSpiel.exe (nur Setup)"><select id="app-pricing"><option value="free">Kostenlos</option><option value="paid">Key benötigt</option></select><button class="primary" type="submit">Spiel veröffentlichen</button></form>'
if old_form in s:
    s = s.replace(old_form, new_form, 1)

old_upload = "const g={title:document.getElementById('app-title').value.trim(),description:document.getElementById('app-desc').value.trim(),coverUrl:document.getElementById('app-cover').value.trim(),downloadUrl:document.getElementById('app-download').value.trim(),version:document.getElementById('app-version').value.trim()||'1.0.0',pricing:document.getElementById('app-pricing').value,createdAt:firebase.firestore.FieldValue.serverTimestamp(),publishedBy:currentUser};"
new_upload = "const installType=document.getElementById('app-install-type')?.value||'direct';const g={title:document.getElementById('app-title').value.trim(),description:document.getElementById('app-desc').value.trim(),coverUrl:document.getElementById('app-cover').value.trim(),downloadUrl:document.getElementById('app-download').value.trim(),version:document.getElementById('app-version').value.trim()||'1.0.0',installType,runInstaller:installType==='setup',postInstallExecutable:document.getElementById('app-post-install-exe')?.value.trim()||'',pricing:document.getElementById('app-pricing').value,createdAt:firebase.firestore.FieldValue.serverTimestamp(),publishedBy:currentUser};"
if old_upload in s:
    s = s.replace(old_upload, new_upload, 1)

index.write_text(s, encoding='utf-8')

print('Setup-game support patched: admin can publish Setup/Installer games; launcher waits for setup and launches the configured game EXE.')
